### ISSUE TITLE
Inline elements don't move until drag ends

### ISSUE THREAD

**Issue by nnodot** [desandro/draggabilly#69] opened 2014-12-02 17:27 UTC
An inline element (say a `<span>`) on which one applies draggabilly doesn't move during drag. Its position actually changes when drag is finished. Styling the element with a `display: block` (or a `display: inline-block`) make it work as expected. Here a code snippet that illustrates this:
```html
<html>
    <head>
        <script type="text/javascript" src="draggabilly.js"></script>
        <style>
            span {
                background: #ddd;
                margin: 5px;
                padding: 5px;
            }
        </style>
    </head>
    <body>
        <span id="jumping-span">
            I am a span and I don't move during drag.
        </span>

        <span id="sliding-span" style="display:inline-block;">
            I am a span too, but I move during drag because I got a
            "display:inline-block".
        </span>
        <script>
            window.onload = function() {
                new Draggabilly( document.querySelector('#jumping-span') );
                new Draggabilly( document.querySelector('#sliding-span') );
            }
        </script>
    </body>
</html>
```
This is due to the fact that during move draggabilly uses css tranforms which don't apply to inline elements. More info [here](http://dev.w3.org/csswg/css-transforms/) in particular on which elements are "transformable elements" (see section "4. Terminology").

**Comment by mcanthony** [comment] 2015-02-28 11:55
+1 and IMO this is an important library that I consider a core library in the realm of jQuery and the like. As such I think it is important to eliminate issues like this even if very few people (because of the typical use of the library due to it's popularity and therefore audience) actually run into the bug.

Unless we are not using the library properly or the method we have chosen is not the optimal one, in which case we as users should use a better method, but we should ideally not have to enact work-around when using the library as it was intended even if the intended use is not a common one.

I suspect no one has reported this issue because if a user is utilizing custom elements (which are newish) and furthermore seeking to dynamically manipulate these elements, they likely know how to work it out themselves and would not bother to report. Not to mention they might not have noticed (yet) until they test something that happens inline by default.

In my case I am writing a builder where numerous polymer/xtags/custom elements are smade available for arbitrary use placement.

I would like to evaluate if the methodology we are using would be considered less than ideal, and if it is ideal then is the proposed patch of logic in the library the most elegant solution? Maybe there is another way to attack this without adding "edge case logic" - something that falls into place naturally...

**Comment by desandro** [comment] 2015-12-28 01:56
Closing this issue as it didn't get additional interest. :whale:

**Closed by desandro** 2015-12-28 01:56 UTC
