### ISSUE TITLE
Itens outside containment

### ISSUE THREAD

**Issue by flastowizka** [desandro/draggabilly#196] opened 2018-07-25 17:16 UTC
Hello,

I have multiple draggable for my containment. I have a free space, but this was put the elements outside of my containment.

![image](https://user-images.githubusercontent.com/8594300/43216154-8ae844b4-9014-11e8-9ea8-5c4f972b5685.png)

When i click in side a box and start to drag the box adjust automatically to inside containment:

![image](https://user-images.githubusercontent.com/8594300/43216170-9b482f86-9014-11e8-84c5-b817dfe2c0b0.png)

Have any function with to "recalculate" this itens ?

**Test case:** https://codepen.io/flastowizka/pen/qyjeML

**Comment by desandro** [comment] 2018-07-25 18:50
Thanks for reporting this issue. This is a duplicate of #34. Add your 👍 there!

**Closed by desandro** 2018-07-25 18:50 UTC
