### ISSUE TITLE
Is there a way to pause/stop dragging?

### ISSUE THREAD

**Issue by neonwired** [desandro/draggabilly#151] opened 2017-02-22 13:03 UTC
Rather than use disable, I want to pause dragging on certain conditions.

Alternatively can you bind a draggable element to a smaller parent?

**Comment by desandro** [comment] 2017-02-24 01:40
Thanks for submitting this issue.

> Rather than use disable, I want to pause dragging on certain conditions.

I'm having trouble understanding what you're trying to do. Can you elaborate? Or better yet provide a [reduced test case](https://github.com/desandro/draggabilly/blob/master/contributing.md#reduced-test-case-required)

**Comment by desandro** [comment] 2018-03-09 19:19
Closing as a duplicate of #177

**Closed by desandro** 2018-03-09 19:19 UTC
