### ISSUE TITLE
Method to update position

### ISSUE THREAD

**Issue by franciscolourenco** [desandro/draggabilly#147] opened 2017-01-08 00:47 UTC
Would be useful to have a method to set the position programatically. 

Related to #146

**Comment by cmalven** [comment] 2017-01-29 21:01
I have a use for this as well. Currently there doesn't seem to be any way to manually update the draggable's position. Even the following results in strange behavior:

```js
    var el = document.querySelector('.my-element);
    var position = 50;
    self.draggable.position.x = position;
    playheadEl.style.left = position + 'px';
```

**Comment by desandro** [comment] 2017-02-10 04:28
You can set position with `left/top` CSS. See demo http://codepen.io/desandro/pen/mRQdwZ

``` js
// jQuery
$draggable.css({
  left: 200,
  top: 100
});

// vanilla JS
dragElem.style.left = '200px';
dragElem.style.top = '100px';
```

**Comment by aristidesfl** [comment] 2017-02-10 15:47
The problem is Dragabilly.position doesn't get updated

**Comment by aristidesfl** [comment] 2017-02-10 15:55
@cmalven :)

So this issue a proposal for an abstraction which allows you to update both at once. 

Either with setters:
```
draggable.position.x = x
draggable.position.y = y
```

Or with a method
```
draggable.setPosition(x, y)
```

Or both

**Comment by desandro** [comment] 2017-02-10 22:19
How about:

``` js
Draggabilly.prototype.setPosition = function( x, y ) {
  this.position.x = x;
  this.position.y = y;
  this.setLeftTop();
};

// then use
draggie.setPosition( 200, 100 )
```

See demo http://codepen.io/desandro/pen/qRQYYB

*Add a 👍  reaction* if you would like to see this feature added to Draggabilly.

**Comment by mubaidr** [comment] 2017-02-23 07:44
Works fine! Thank you! 👍

**Comment by desandro** [comment] 2018-03-27 15:40
🎉 [Draggabilly v2.2.0](https://github.com/desandro/draggabilly/releases/tag/v2.2.0) has been released new [`setPosition` method](https://draggabilly.desandro.com/#setposition) added. 🎉

Please update! Closing this feature request as resolved. Please open a new issue if you run into trouble with `setPosition`. Thanks all for the feedback!

**Closed by desandro** 2018-03-27 15:40 UTC
Labels: feature request
